version: '3'

services:
  app:
    container_name: movie_rankings
    hostname: movie_rankings
    restart: always
    build: ./
    env_file:
      - .env
    ports:
      - 9003:80
      - 19003:443
