#!/usr/bin/env bash
source env/bin/activate
export APP_SECRET_KEY=debug_key
export FACEBOOK_CLIENTID=_____________USE_PRODUCTION_SITE_SEE_README____________
export FACEBOOK_SECRET=____________USE_PRODUCTION_SITE_SEE_README____________
env/bin/python movie_rankings/core.py
