call env\Scripts\Activate
set APP_SECRET_KEY=debug_key
set FACEBOOK_CLIENTID=_____________USE_PRODUCTION_SITE_SEE_README____________
set FACEBOOK_SECRET=____________USE_PRODUCTION_SITE_SEE_README____________
env\Scripts\python movie_rankings/core.py