apiVersion: networking.k8s.io/v1beta1
kind: Ingress
metadata:
  name: "{{ .Chart.Name }}-ingress"
  annotations:
    kubernetes.io/ingress.class: nginx
    nginx.ingress.kubernetes.io/backend-protocol: HTTP
    nginx.com/health-checks: "true"
    nginx.ingress.kubernetes.io/rewrite-target: /$1
    nginx.ingress.kubernetes.io/affinity: cookie
    nginx.ingress.kubernetes.io/session-cookie-expires: "360"
    nginx.ingress.kubernetes.io/session-cookie-max-age: "360"
spec:
  rules:
  - host: {{ .Values.host }}
    http:
      paths:
      - path: /(.*)
        pathType: Prefix
        backend:
          serviceName: {{ .Chart.Name }}
          servicePort: {{ .Values.port }}
