apiVersion: kubernetes-client.io/v1
kind: ExternalSecret
metadata:
  name: {{ .Chart.Name }}
spec:
  backendType: secretsManager
  data:
    - key: {{ .Values.secret }}
      name: app-secret-key
      property: projects.movieRankings.appSecretKey
    - key: {{ .Values.secret }}
      name: facebook-clientid
      property: projects.movieRankings.facebookClientId
    - key: {{ .Values.secret }}
      name: facebook-secret
      property: projects.movieRankings.facebookSecret
    - key: {{ .Values.secret }}
      name: themoviedb-key
      property: projects.movieRankings.theMovieDbKey
