apiVersion: kubernetes-client.io/v1
kind: ExternalSecret
metadata:
  name: {{ .Chart.Name }}
spec:
  backendType: systemManager
  data:
    - key: {{ .Values.secret }}
      name: app-secret-key
      property: appSecretKey
    - key: {{ .Values.secret }}
      name: facebook-clientid
      property: facebookClientId
    - key: {{ .Values.secret }}
      name: facebook-secret
      property: facebookSecret
    - key: {{ .Values.secret }}
      name: themoviedb-key
      property: theMovieDbKey
