apiVersion: v1
kind: Service
metadata:
  name: {{ .Chart.Name }}
  labels:
    svc: {{ .Chart.Name }}
spec:
  ports:
  - protocol: TCP
    port: {{ .Values.port }}
    targetPort: {{ .Values.port }}
  selector:
    app: {{ .Chart.Name }}
