apiVersion: v1
kind: Service
metadata:
  name: "{{ .Chart.Name }}-service"
  labels:
    app: {{ .Chart.Name }}
  annotations:
    kubernetes.digitalocean.com/firewall-managed: "false"
spec:
  type: NodePort
  selector:
    app: {{ .Chart.Name }}
  ports:
    - name: http
      port: {{ $.Values.port }}
      nodePort: {{ $.Values.nodePort }}
